 public class Operation2 extends Exception{  
 int data=50,data2=30;

 static int c=0;
 public Operation2(String s)
 {
    super(s);
 }
  
  
 void change(Operation2 op){  
 op.data=op.data+100;
 }  
     void change1(int data){  
 data2=data2+100;
 }  
static void rec() throws Operation2{    
         
            
       c++;
        if(c>3)
           {throw new Operation2("c is greater than 3");  } 
       else
        {System.out.println(c);  }
        
         rec();
        }
    
 public static void main(String args[])
 throws ClassNotFoundException
    {
 try {
           
           Class temp=Class.forName("Operation2");
           int b=20; 
Integer j=Integer.valueOf(b);

System.out.println(b+" "+j);  
            }
        catch (ClassNotFoundException e) {
           
            System.out.println(
                "Class does not exist check the name of the class");
        }
     
   Operation2 op=new Operation2("c is less than 3");  
 
   System.out.println("before change "+op.data);  
   op.change(op);
   System.out.println("after change "+op.data);  
   System.out.println("before change "+op.data2);  
   op.change1(500);  
   System.out.println("after change "+op.data2);  
    
   int a[]={33,3,4,5};
for(int i=0;i<a.length;i++)
System.out.println(a[i]);  
try{
System.out.println(a[2]/0);
}catch(ArithmeticException e){System.out.println(e);}  
    
 try{
rec();
}
catch( Operation2 ex)  
        {  
            System.out.println("Caught the exception");  
     System.out.println("Exception occured: " + ex);  
        }  

   
  
 }  
}  