<?xml version="1.0" encoding="UTF-8"?><testrun name="RunTest (1)" project="Cucumberproject" tests="1" started="1" failures="0" errors="1" ignored="0">
  <testsuite name="dataTable.RunTest" time="0.0">
    <testcase name="initializationError" classname="dataTable.RunTest" time="0.0">
      <error>gherkin.parser.ParseError: Parse error at dataTable\login.feature:2. Found scenario when expecting one of: comment, feature, tag. (Current getState: root).&#13;
	at gherkin.parser.Parser$Machine.event(Parser.java:208)&#13;
	at gherkin.parser.Parser.event(Parser.java:160)&#13;
	at gherkin.parser.Parser.scenario(Parser.java:103)&#13;
	at gherkin.lexer.i18n.EN.scan(EN.java:673)&#13;
	at gherkin.lexer.I18nLexer.scan(I18nLexer.java:30)&#13;
	at gherkin.parser.Parser.parse(Parser.java:57)&#13;
	at cucumber.runtime.FeatureBuilder.parse(FeatureBuilder.java:112)&#13;
	at cucumber.runtime.model.CucumberFeature.load(CucumberFeature.java:40)&#13;
	at cucumber.runtime.RuntimeOptions.cucumberFeatures(RuntimeOptions.java:82)&#13;
	at cucumber.junit.Cucumber.&lt;init&gt;(Cucumber.java:60)&#13;
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)&#13;
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)&#13;
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)&#13;
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)&#13;
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)&#13;
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:31)&#13;
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:24)&#13;
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:57)&#13;
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:29)&#13;
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:57)&#13;
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:24)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createUnfilteredTest(JUnit4TestLoader.java:90)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:76)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:49)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:513)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)&#13;
&#13;
</error>
    </testcase>
  </testsuite>
</testrun>
